<?php

namespace CollDev\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentMethodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentMethodsRepository extends EntityRepository
{
}
